### ISSUE TITLE
Stop gesture swiping and sort list

### ISSUE THREAD

**Issue by lamatat** [geekruchika/FlutterCardSwipe#2]
Greetings,

I have two issues: 

**FIRST:**

i want to remove the feature to swipe by gesture .. i tried to remove:

`GestureDetector() 
`from the activeCard class .. but its still there

how to remove this feature? i just want the animation to be on a button click .. no gesture

**SECOND:**

Also, i noticed that the first item in the list (activeCard) is actually the last item in the list .. since it's done like this:

```
if (data.indexOf(item) == data.length - 1) {
                  return cardDemo();
                } else {
                  return cardDemoDummy();
                }
```
how to make the first is the first item in the list or sort the items in the list in reverse?

how to fix these two points?
waiting for your reply.
Thank you.

**Comment by geekruchika** [comment]
1. Remove Dismissible widget from active_card not  `GestureDetector()`
2. Just reverse the data before mapping it into Stack.
 Stack(
                  children: data.reversed.map((item) { })

@lamatat
